#!/bin/bash

if [ -z ${LIBCONF+x} ]; then
	LIBCONF=include/lightmodbus/libconf.h
fi;
>>$LIBCONF;

if [ -z ${BUILDLOG+x} ]; then
	BUILDLOG=build.log
fi;
>>$BUILDLOG;

echo -e "/*" >> $LIBCONF
echo -e "\tThis file gets automatically generated by makefile" >> $LIBCONF
echo -e "" >> $LIBCONF
echo -e "\tIts purpose is to configure each liblightmodbus header file," >> $LIBCONF
echo -e "\tso the user does not have to pass tons of compiler options each time" >> $LIBCONF
echo -e "\the/she wants to compile the library." >> $LIBCONF
echo -e "\tIt also serves as a pretty nice source of information about current" >> $LIBCONF
echo -e "\tlibrary setup." >> $LIBCONF
echo -e "" >> $LIBCONF
echo -e "\tDo not edit this file manually unless you know what you are doing." >> $LIBCONF
echo -e "*/" >> $LIBCONF
echo -e "#ifndef LIGHTMODBUS_LIBCONF_H" >> $LIBCONF
echo -e "#define LIGHTMODBUS_LIBCONF_H" >> $LIBCONF

printf "[staticmem] slave request - " >> $BUILDLOG
if [ -z $STATICMEM_SREQUEST ]; then
	echo "dynamic" >> $BUILDLOG
else
	echo "$STATICMEM_SREQUEST bytes" >> $BUILDLOG
	echo "#define LIGHTMODBUS_STATICMEM_SLAVE_REQUEST $STATICMEM_SREQUEST" >> $LIBCONF
fi;

printf "[staticmem] slave response - " >> $BUILDLOG
if [ -z $STATICMEM_SRESPONSE ]; then
	echo "dynamic" >> $BUILDLOG
else
	echo "$STATICMEM_SRESPONSE bytes" >> $BUILDLOG
	echo "#define LIGHTMODBUS_STATICMEM_SLAVE_RESPONSE $STATICMEM_SRESPONSE" >> $LIBCONF
fi;

printf "[staticmem] master request - " >> $BUILDLOG
if [ -z $STATICMEM_MREQUEST ]; then
	echo "dynamic" >> $BUILDLOG
else
	echo "$STATICMEM_MREQUEST bytes" >> $BUILDLOG
	echo "#define LIGHTMODBUS_STATICMEM_MASTER_REQUEST $STATICMEM_MREQUEST" >> $LIBCONF
fi;

printf "[staticmem] master response - " >> $BUILDLOG
if [ -z $STATICMEM_MRESPONSE ]; then
	echo "dynamic" >> $BUILDLOG
else
	echo "$STATICMEM_MRESPONSE bytes" >> $BUILDLOG
	echo "#define LIGHTMODBUS_STATICMEM_MASTER_RESPONSE $STATICMEM_MRESPONSE" >> $LIBCONF
fi;

printf "[staticmem] master data - " >> $BUILDLOG
if [ -z $STATICMEM_MDATA ]; then
	echo "dynamic" >> $BUILDLOG
else
	echo "$STATICMEM_MDATA bytes" >> $BUILDLOG
	echo "#define LIGHTMODBUS_STATICMEM_MASTER_DATA $STATICMEM_MDATA" >> $LIBCONF
fi;


#Manage modules
functions=(01 02 03 04 05 06 15 16 22)

case $SMODULES in
	*forcebase*)
		addbase=true
		;;
	*)
		addbase=false
		;;
esac;

for i in "${functions[@]}"; do
	if echo $SMODULES | grep -q $i; then
		printf "#define LIGHTMODBUS_F%sS\n" $i >> $LIBCONF
		echo "[x] slave $i" >> $BUILDLOG
		case $i in
			01)
				echo "slave-coils"
				addbase=true
				;;
			02)
				echo "slave-coils"
				addbase=true
				;;
			03)
				echo "slave-registers"
				addbase=true
				;;
			04)
				echo "slave-registers"
				addbase=true
				;;
			05)
				echo "slave-coils"
				addbase=true
				;;
			06)
				echo "slave-registers"
				addbase=true
				;;
			15)
				echo "slave-coils"
				addbase=true
				;;
			16)
				echo "slave-registers"
				addbase=true
				;;
			22)
				echo "slave-registers"
				addbase=true
				;;
		esac;
	else
		echo "[ ] slave $i" >> $BUILDLOG
	fi
done
if [ "$addbase" == "true" ]; then
	echo "slave-base slave-link"
	echo "[info] slave base is going to be included" >> $BUILDLOG
else
	echo "[warning] skipping slave base" >> $BUILDLOG
fi;


case $MMODULES in
	*forcebase*)
		addbase=true
		;;
	*)
		addbase=false
		;;
esac;

for i in "${functions[@]}"; do
	if echo $MMODULES | grep -q $i; then
		printf "#define LIGHTMODBUS_F%sM\n" $i >> $LIBCONF
		echo "[x] master $i" >> $BUILDLOG
		case $i in
			01)
				echo "master-coils"
				addbase=true
				;;
			02)
				echo "master-coils"
				addbase=true
				;;
			03)
				echo "master-registers"
				addbase=true
				;;
			04)
				echo "master-registers"
				addbase=true
				;;
			05)
				echo "master-coils"
				addbase=true
				;;
			06)
				echo "master-registers"
				addbase=true
				;;
			15)
				echo "master-coils"
				addbase=true
				;;
			16)
				echo "master-registers"
				addbase=true
				;;
			22)
				echo "master-registers"
				addbase=true
				;;
		esac;
	else
		echo "[ ] master $i" >> $BUILDLOG
	fi
done
if [ "$addbase" == "true" ]; then
	echo "master-base master-link"
	echo "[info] master base is going to be included" >> $BUILDLOG
else
	echo "[warning] skipping master base" >> $BUILDLOG
fi;

echo "#endif" >> $LIBCONF
