#!/bin/bash

if [ -z ${LIBCONF+x} ]; then
	LIBCONF=include/lightmodbus/libconf.h
fi;
>$LIBCONF;

if [ -z ${BUILDLOG+x} ]; then
	BUILDLOG=build.log
fi;
>$BUILDLOG;

echo "/*" >> $LIBCONF
echo "\tThis file gets automatically generated by makefile" >> $LIBCONF
echo "" >> $LIBCONF
echo "\tIts purpose is to configure each liblightmodbus header file," >> $LIBCONF
echo "\tso the user does not have to pass tons of compiler options each time" >> $LIBCONF
echo "\the/she wants to compile the library." >> $LIBCONF
echo "\tIt also serves as a pretty nice source of information about current" >> $LIBCONF
echo "\tlibrary setup." >> $LIBCONF
echo "" >> $LIBCONF
echo "\tDo not edit this file manually unless you know what you are doing." >> $LIBCONF
echo "*/" >> $LIBCONF
echo "#ifndef LIGHTMODBUS_LIBCONF_H" >> $LIBCONF
echo "#define LIGHTMODBUS_LIBCONF_H" >> $LIBCONF


printf "[staticmem] slave request - " >> $BUILDLOG
if [ -z ${STATICMEM_SREQUEST+x} ]; then
	echo "dynamic" >> $BUILDLOG
else
	echo "$STATICMEM_SREQUEST bytes" >> $BUILDLOG
	echo "#define LIGHTMODBUS_STATICMEM_SLAVE_REQUEST $STATICMEM_SREQUEST" >> $LIBCONF
fi;

printf "[staticmem] slave response - " >> $BUILDLOG
if [ -z ${STATICMEM_SRESPONSE+x} ]; then
	echo "dynamic" >> $BUILDLOG
else
	echo "$STATICMEM_SRESPONSE bytes" >> $BUILDLOG
	echo "#define LIGHTMODBUS_STATICMEM_SLAVE_RESPONSE $STATICMEM_SRESPONSE" >> $LIBCONF
fi;

printf "[staticmem] master request - " >> $BUILDLOG
if [ -z ${STATICMEM_MREQUEST+x} ]; then
	echo "dynamic" >> $BUILDLOG
else
	echo "$STATICMEM_MREQUEST bytes" >> $BUILDLOG
	echo "#define LIGHTMODBUS_STATICMEM_MASTER_REQUEST $STATICMEM_MREQUEST" >> $LIBCONF
fi;

printf "[staticmem] master response - " >> $BUILDLOG
if [ -z ${STATICMEM_MRESPONSE+x} ]; then
	echo "dynamic" >> $BUILDLOG
else
	echo "$STATICMEM_MRESPONSE bytes" >> $BUILDLOG
	echo "#define LIGHTMODBUS_STATICMEM_MASTER_RESPONSE $STATICMEM_MRESPONSE" >> $LIBCONF
fi;

printf "[staticmem] master data - " >> $BUILDLOG
if [ -z ${STATICMEM_MDATA+x} ]; then
	echo "dynamic" >> $BUILDLOG
else
	echo "$STATICMEM_MDATA bytes" >> $BUILDLOG
	echo "#define LIGHTMODBUS_STATICMEM_MASTER_DATA $STATICMEM_MDATA" >> $LIBCONF
fi;

echo "" >> $BUILDLOG

#Manage modules
functions=(01 02 03 04 05 06 15 16 22)
for i in "${functions[@]}"; do
	if echo $SMODULES | grep -q $i; then
		printf "#define LIGHTMODBUS_F%sS\n" $i >> $LIBCONF
		echo "[x] slave $i" >> $BUILDLOG
	else
		echo "[ ] slave $i" >> $BUILDLOG
	fi
done
echo "" >> $BUILDLOG
for i in "${functions[@]}"; do
	if echo $MMODULES | grep -q $i; then
		printf "#define LIGHTMODBUS_F%sM\n" $i >> $LIBCONF
		echo "[x] master $i" >> $BUILDLOG
	else
		echo "[ ] master $i" >> $BUILDLOG
	fi
done

echo "#endif" >> $LIBCONF
