# liblightmodbus - a lightweight, multiplatform Modbus library
# Copyright (C) 2016 Jacek Wieczorek <mrjjot@gmail.com>

# This file is part of liblightmodbus.

# Liblightmodbus is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Liblightmodbus is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# This is makefile for liblightmodbus - a lightweight Modbus library
# It creates object files and a static library, so you can link it to your project
# If you want, liblightmodbus can be installed on your system using 'make install', or later removed using 'make uninstall'
# If you want to build it yourself for platform like AVR, this is not the makefile you are looking for
# Beside, files building order is cruicial - modules first, then base, and finally linking, otherwise things will go wrong

# This makefile is part of source deb package

compileHeader = \
	echo "[\033[32;1mcompiling\033[0m] \033[03m$(1)\033[0m" >&2

linkHeader = \
	echo "[\033[33;1mlinking\033[0m] \033[03m$(1)\033[0m" >&2

errorHeader = \
	echo "[\033[31;1merror\033[0m] \033[03m$(1)\033[0m" >&2

cleanHeader = \
	echo "[\033[36;1mcleaning up\033[0m] \033[03m$(1)\033[0m" >&2

infoHeader = \
	echo "[\033[36;1minfo\033[0m] \033[03m$(1)\033[0m" >&2

ARCH = $(shell arch)
CC = gcc
CFLAGS = -Wall -I./include
LD = ld
LDFLAGS =
AR = ar

MODULES =
SMODULES = 01 02 03 04 05 06 15 16 22
MMODULES = 01 02 03 04 05 06 15 16 22

STATICMEM_SREQUEST =
STATICMEM_SRESPONSE =
STATICMEM_MREQUEST =
STATICMEM_MRESPONSE =
STATICMEM_MDATA =

UPDATECFG =
ifeq ($(MAKECMDGOALS),all)
UPDATECFG = true
endif
ifeq ($(MAKECMDGOALS),)
UPDATECFG = true
endif
ifdef UPDATECFG
$(file >include/lightmodbus/libconf.h,/*)
$(file >>include/lightmodbus/libconf.h,	--This file gets automatically generated by makefile--)
$(file >>include/lightmodbus/libconf.h,)
$(file >>include/lightmodbus/libconf.h,	Its purpose is to configure each liblightmodbus header file,)
$(file >>include/lightmodbus/libconf.h,	so the user does not have to pass tons of compiler options each time)
$(file >>include/lightmodbus/libconf.h,	he/she wants to compile the library.)
$(file >>include/lightmodbus/libconf.h,	It also serves as a pretty nice source of information about current)
$(file >>include/lightmodbus/libconf.h,	library setup.)
$(file >>include/lightmodbus/libconf.h,)
$(file >>include/lightmodbus/libconf.h,	Do not edit this file manually unless you know what you are doing.)
$(file >>include/lightmodbus/libconf.h,*/)
$(file >>include/lightmodbus/libconf.h,#ifndef LIGHTMODBUS_LIBCONF)
$(file >>include/lightmodbus/libconf.h,#define LIGHTMODBUS_LIBCONF)
$(file >>include/lightmodbus/libconf.h,)
include .makefile-staticmem
include .makefile-modules
$(file >>include/lightmodbus/libconf.h,)
$(file >>include/lightmodbus/libconf.h,#endif)
endif

all: $(MODULES)
all: clean force core
	$(call linkHeader,full object file)
	echo "LINKING Library full object file (obj/lightmodbus.o)" >> build.log
	$(LD) $(LDFLAGS) -r obj/*.o -o obj/lightmodbus.o
	$(call linkHeader,static library file)
	echo "CREATING Static library file (lib/liblightmodbus.a)" >> build.log
	$(AR) -cvq lib/liblightmodbus.a obj/lightmodbus.o
	$(AR) -t  lib/liblightmodbus.a
	echo -n "\n\nBuild success - " >> build.log
	date >> build.log
	$(call infoHeader,build finished successfully)

install:
	$(call infoHeader,installing liblightmodbus)
	-mkdir -p $(DESTDIR)/usr
	-mkdir -p $(DESTDIR)/usr/include
	cp -R include/lightmodbus $(DESTDIR)/usr/include
	-mkdir $(DESTDIR)/usr/lib
	cp -R lib/liblightmodbus.a $(DESTDIR)/usr/lib

uninstall:
	$(call infoHeader,removing liblightmodbus)
	rm -rf $(DESTDIR)/usr/include/lightmodbus
	rm -f $(DESTDIR)/usr/lib/liblightmodbus.a

force:
	$(call infoHeader,starting build)
	-touch build.log
	echo -n "Architecture: " > build.log
	echo $(ARCH) >> build.log
	echo -n "Build started - " >> build.log
	date >> build.log
	echo -n "\n\n" >> build.log
	-mkdir obj
	-mkdir obj/slave
	-mkdir obj/master
	-mkdir lib

clean:
	$(call infoHeader,cleaning up build environment)
	-find . -name "*.gch" -type f -delete
	-rm -rf obj
	-rm -rf lib
	-rm -f build.log
	-rm -f *.gcno
	-rm -f *.gcda
	-rm -f *.o
	-rm -f coverage-test
	-rm -f coverage-test.log
	-rm -f valgrind.xml
	-rm -f massif.out

################################################################################

core: src/core.c include/lightmodbus/core.h
	$(call compileHeader,core module)
	echo "COMPILING Core module (obj/core.o)" >> build.log
	$(CC) $(CFLAGS) -c src/core.c -o obj/core.o

master-base: src/master.c include/lightmodbus/master.h
	$(call compileHeader,master base module)
	echo "COMPILING Master module (obj/master/mbase.o)" >> build.log
	$(CC) $(CFLAGS) -c src/master.c -o obj/master/mbase.o

master-registers: src/master/mpregs.c include/lightmodbus/master/mpregs.h src/master/mbregs.c include/lightmodbus/master/mbregs.h
	$(call compileHeader,master registers module)
	echo "COMPILING Master registers module (obj/master/mregisters.o)" >> build.log
	$(CC) $(CFLAGS) -c src/master/mpregs.c -o obj/master/mpregs.o
	$(CC) $(CFLAGS) -c src/master/mbregs.c -o obj/master/mbregs.o

master-coils: src/master/mpcoils.c include/lightmodbus/master/mpcoils.h src/master/mbcoils.c include/lightmodbus/master/mbcoils.h
	$(call compileHeader,master coils module)
	echo "COMPILING Master coils module (obj/master/mcoils.o)" >> build.log
	$(CC) $(CFLAGS) -c src/master/mpcoils.c -o obj/master/mpcoils.o
	$(CC) $(CFLAGS) -c src/master/mbcoils.c -o obj/master/mbcoils.o

master-link:
	$(call linkHeader,master modules)
	echo "LINKING Master module (obj/master.o)" >> build.log
	$(LD) $(LDFLAGS) -r obj/master/*.o -o obj/master.o

slave-base: src/slave.c include/lightmodbus/slave.h
	$(call compileHeader,slave base module)
	echo "COMPILING Slave module (obj/slave/sbase.o)" >> build.log
	$(CC) $(CFLAGS) -c src/slave.c -o obj/slave/sbase.o

slave-registers: src/slave/sregs.c include/lightmodbus/slave/sregs.h
	$(call compileHeader,slave registers module)
	echo "COMPILING Slave registers module (obj/slave/sregisters.o)" >> build.log
	$(CC) $(CFLAGS) -c src/slave/sregs.c -o obj/slave/sregs.o

slave-coils: src/slave/scoils.c include/lightmodbus/slave/scoils.h
	$(call compileHeader,slave coils module)
	echo "COMPILING Slave coils module (obj/slave/scoils.o)" >> build.log
	$(CC) $(CFLAGS) -c src/slave/scoils.c -o obj/slave/scoils.o

slave-link:
	$(call linkHeader,slave modules)
	echo "LINKING Slave module (obj/slave.o)" >> build.log
	$(LD) $(LDFLAGS) -r obj/slave/*.o -o obj/slave.o
