#!/bin/bash

cd man

for f in *.md; do
  md2man-roff ./"$f" > ./"${f%.md}"
done

cp modbusBuildRequest.3lightmodbus modbusBuildRequest01.3lightmodbus
cp modbusBuildRequest.3lightmodbus modbusBuildRequest02.3lightmodbus
cp modbusBuildRequest.3lightmodbus modbusBuildRequest03.3lightmodbus
cp modbusBuildRequest.3lightmodbus modbusBuildRequest04.3lightmodbus
cp modbusBuildRequest.3lightmodbus modbusBuildRequest05.3lightmodbus
cp modbusBuildRequest.3lightmodbus modbusBuildRequest06.3lightmodbus
cp modbusBuildRequest.3lightmodbus modbusBuildRequest15.3lightmodbus
cp modbusBuildRequest.3lightmodbus modbusBuildRequest16.3lightmodbus

cp modbusParseRequest.3lightmodbus modbusParseRequest01.3lightmodbus
cp modbusParseRequest.3lightmodbus modbusParseRequest02.3lightmodbus
cp modbusParseRequest.3lightmodbus modbusParseRequest03.3lightmodbus
cp modbusParseRequest.3lightmodbus modbusParseRequest04.3lightmodbus
cp modbusParseRequest.3lightmodbus modbusParseRequest05.3lightmodbus
cp modbusParseRequest.3lightmodbus modbusParseRequest06.3lightmodbus
cp modbusParseRequest.3lightmodbus modbusParseRequest15.3lightmodbus
cp modbusParseRequest.3lightmodbus modbusParseRequest16.3lightmodbus

cp modbusParseResponse.3lightmodbus modbusParseResponse01.3lightmodbus
cp modbusParseResponse.3lightmodbus modbusParseResponse02.3lightmodbus
cp modbusParseResponse.3lightmodbus modbusParseResponse03.3lightmodbus
cp modbusParseResponse.3lightmodbus modbusParseResponse04.3lightmodbus
cp modbusParseResponse.3lightmodbus modbusParseResponse05.3lightmodbus
cp modbusParseResponse.3lightmodbus modbusParseResponse06.3lightmodbus
cp modbusParseResponse.3lightmodbus modbusParseResponse15.3lightmodbus
cp modbusParseResponse.3lightmodbus modbusParseResponse16.3lightmodbus
